### ISSUE TITLE
[BUG] language switch not working

### ISSUE THREAD

**Issue by fmacherey** [Usercentrics/react-native-sdk#11]
**Describe the bug**
When testing the options, we found out, that the language switch is not working. We have german (default lang), dutch and english, but always get the german CMP popup. I used "en", "english" or "English" as values, but every time the popup is still in german.

We use our locale from react-intl package, which is "de", "nl" or "en", depending on system language of the device.

**usercentrics/react-native branch/commit**
v0.0.3, iOS, Android not tested yet

**Comment by uc-pedro** [comment]
Hello @fmacherey Thanks for opening the ticket, we will investigate the issue and fix it as soon as possible.

**Comment by fmacherey** [comment]
@uc-pedro I adjusted the title, as it was regarding to the other issue, you already fixed :)

**Comment by uc-pedro** [comment]
@fmacherey I was looking into our code and regarding the language, we have a few steps:

First, we check if the user has any language stored from previous sessions;
If there is no previous language, we fallback to the default language provided via code;
If there is no previous language, we fallback to the device language; 
If we can't fetch the device language, we fallback to the first language that you have configured on our admin interface.

Here you can see a more detailed graph with this explanation: 
https://docs.usercentrics.com/cmp_in_app_sdk/latest/getting_started/configure/#language-selection-hierarchy

So in your case, you would need to call the reset function or to clear the storage in order to fallback to the provided language.

**Comment by fmacherey** [comment]
Yes this works. I reseted the CMP and than I also get a appropriate CMP.
