### ISSUE TITLE
[BUG] Usercentrics initialization failed: - Something went wrong while fetching the available languages. - Failed to read from cache, key: languages

### ISSUE THREAD

**Issue by DominikHinc** [Usercentrics/react-native-sdk#42]
**Describe the bug**
We are getting a lot of "Usercentrics initialization failed: - Something went wrong while fetching the available languages. - Failed to read from cache, key: languages" issues in our error tracking system.

**To Reproduce**
Not sure, I have never managed to reproduce this, but a lot of our users do trigger this.

**Expected behavior**
It shouldn't throw those errors

If this is intended behaviour, could I at least get an info of when is this triggered and can it cause some problems for our users?

**Comment by userCTest** [comment]
Hi there @DominikHinc,

that error happens only on the very first initialization of the SDK (say after app install, or a clearing of the app storage). Only then a network connection is required in order to fetch the CMP data from the backend. After this first time, the data is stored in the device and from then on this data will be used on initialization if no network connection is present (so it will work as a fallback if no internet connection is available when the CMP is launched). 

Could you maybe provide us with some logs, stacktraces so we can have a closer look?

**Comment by DominikHinc** [comment]
It's appearing on both platforms, but now that I know when it happens I think this is an expected behaviour. Thank you for clarification.

**Comment by userCTest** [comment]
Cool, if there's anything else you need, just let us know ;) Cheers, rui
