### ISSUE TITLE
[BUG] Updated TCF String is not stored at the time callback with updated consents is invoked

### ISSUE THREAD

**Issue by Elrohil44** [Usercentrics/react-native-sdk#59]
**Describe the bug**
It often happens that after collecting the consent the updated TCF string is not yet stored in SharedPreferences. I was trying to find an issue in this library, but I think the problem is in native SDK and is connected with the fact that the data is saved asynchronously

**To Reproduce**
On some devices (we tested for example on Huawei P40, OnePlus 3T and some other Samsung devices):
1. We follow the steps from documentation:
```typescript
const options: FirstLayerOptions = { 
    layout: <UsercentricsLayout> // .full, .sheet, .popup
};

const userResponse = await Usercentrics.showFirstLayer(options);
applyConsent(userResponse.consents);
```
2. When the `applyConsent` is called there is still previous TCF String in SharedPreferences
3. After waiting a while (for example 200ms, we did not check the exact time) the TCF string is updated.

We tested it also on Xiaomi Mi10T and there the problem does not occur.

**Expected behavior**
When the callback with updated consents is invoked (promise is resolved) the updated TCF string should always be available in SharedPreferences

**Screenshots**

**Flutter doctor**

**usercentrics/react-native branch/commit**
- Your fork/commit:
@usercentrics/react-native-sdk@^2.7.6

**Additional context**
After user updates his consents we need to reliably reconfigure 3rd party SDKs with updated consents. Currently it happens that the previous consent string is applied instead of updated one. As a temporary workaround we added a delay of 200ms before calling `applyConsent` but it is a dirty solution and we want to avoid using unreliable solutions

**Comment by uc-nfdz** [comment]
Hello @Elrohil44

The TCF string encoding/decoding and storage are heavy tasks and should happen in the background to avoid performance and UI issues. The showFirstLayer/showSecondLayer callback only returns GDPR-related consents and does not wait for this synchronous job to finish. This is so because TCF does not normally require any integration from the developer, vendors read the consent from SharedPreferences without your intervention. 

If you need to read the updated TCF String I recommend you to use the `getTCFData` method that returns the latest data as soon as it is available. The `TCFData` object has the encoded (`tcString `) and the decoded data (`features`, `purposes `, ...). 
Hope that's what you need.

**Comment by Elrohil44** [comment]
Hey, thank you for the reply. Can you confirm that with this approach we will get the latest TCFData? Or the data that was previously saved in SharedPreferences?
```typescript
const options: FirstLayerOptions = { 
    layout: <UsercentricsLayout> // .full, .sheet, .popup
};

const userResponse = await Usercentrics.showFirstLayer(options);
await Usercentrics.getTCFData(); // <------
applyConsent(userResponse.consents);
```
If that approach does not work, can you suggest an approach to be notified about the TCF data change? Maybe we should create native bridge where we would utilize OnSharedPreferenceChangeListener ([docs](https://developer.android.com/reference/android/content/SharedPreferences.OnSharedPreferenceChangeListener))? Unfortunately one of our SDKs checks the TCF data only after we call one of its methods

**Comment by uc-nfdz** [comment]
Yes, you get the latest TCFData if you do that way. 
I think you are missing the TCF data:
```typescript
const options: FirstLayerOptions = { 
    layout: <UsercentricsLayout> // .full, .sheet, .popup
};

const userResponse = await Usercentrics.showFirstLayer(options);
const tcfData = await Usercentrics.getTCFData();
applyConsent(userResponse.consents, tcfData.tcString);
```
If you are reading the tcfString directly from the SharedPreferences, then you can ignore my suggestion, it's up to you if you want to deal with the SharedPreferences or not.

I didn't want to mention the `OnSharedPreferenceChangeListener`, that's the best approach in the TCF framework for vendors. I think it is a bit more difficult here because you would have to bridge all of that (or use a 3rd party lib with that).

**Comment by Elrohil44** [comment]
It worked. Thank you very much for your feedback. I think I can close the issue now
