### ISSUE TITLE
[iOS] EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by uc-leo** [Usercentrics/react-native-sdk#76]
![](https://user-images.githubusercontent.com/45258735/232058488-8c58857b-0854-494e-9d39-869eff3ef81d.png)

**Comment by uc-leo** [comment]
@km4r hey Marcin!

regarding this issue, is still happening? do you have more insights about it? 

can you confirm that by only doing the upgrade to a newer version of Usercentrics this problem emerges? I'm asking that because we often see a lot of changes being done on customer side, alongside a Usercentrics upgrade, and sometimes the problem are unrelated to us.

thanks in advance!

**Comment by km4r** [comment]
Hey @uc-leo 

yes, the issue is still valid and I'm sure it has something to do with the Usercentrics version. Recently we had to make a downgrade because the crash rate was too high. We use 2.7.1 now, so we miss some important updates of course (like the logo fix and `disableSystemBackButton` option), but the crash rate decreased significantly.

We encounter an increase in numbers after upgrading UC to 2.7.12, but it was an update straight from 2.7.1 to 2.7.12, so I can't tell exactly what version was affected first.

**Comment by km4r** [comment]
Hello, it's been a while :) 

any news on this?

**Comment by uc-leo** [comment]
hello @km4r 

1. can you confirm if you are still relying on an old version of the SDK? 
2. have you tried upgrading it? 
3. have you been able to reproduce the issue?
4. do you have more details about this problem? from that stacktrace it was nearly impossible to reproduce the problem and we chose to prioritize other issues and improvements. if you have more information about it, we'll gladly accept it :)

sorry for the delay on getting back to you. important to say that so far you are the only customer with such problem.

thanks again for reaching out!

**Comment by uc-leo** [comment]
thanks @km4r !

please, do try the latest version and if something arises, I ask you to reopen this issue.

sorry for not providing any more help, but we are also a bit blindfolded on this one :(

thanks again for the comprehension!
